### ISSUE TITLE
french access document is in spanish

### ISSUE THREAD

**Issue by Albirew** [good-lly/gdpr-documents#7]
docs/fr_français/gdpr_access_fr.md
and
docs/fr_français/gdpr_access_fr.pdf
are in spanish.
we can still retrieve older versions here: 
https://github.com/good-lly/gdpr-documents/tree/6974912904ee8cd8e13f457f372a7c2280d683dd/data-access/fr

**Comment by good-lly** [comment]
hmmm ... 🤔  how this could happen?

**Comment by good-lly** [comment]
@Albirew could you please check if docs/fr_français/gdpr_access_fr.md is now correct???

**Comment by Albirew** [comment]
md file is fine but pdf is still in spanish

**Comment by good-lly** [comment]
@Albirew should be fixed now! thank you 🙏
